#%RAML 0.8
---
title: Inheritance Tax Residence Nil Rate Band Calculator Microservice
baseUri: http://localhost:7112/residence-nil-rate-band-calculator

/hello-world:
    get:
        description: Get the "Hello World" repsonse
        responses:
            200:
                body:
                    application/text:
                        example: |
                            Hello World