#%RAML 1.0
title: Inheritance Tax Residence Nil Rate Band Calculator Microservice
baseUri: https://raw.githubusercontent.com/hmrc/residence-nil-rate-band-calculator/RNRBC-RAML/conf
protocols: [ HTTPS ]
mediaType: [ application/json, application/hal+json ]

/calculate:
    post:
        description: |
            Calculates the amount of Residence Nil Rate Band and the Transferable Residence Nil Rate Band for the given estate
        body:
            application/json:
                schema: !include schemas/deceaseds-estate.jsonschema
                example: !include schemas/deceaseds-estate.example
        responses:
            200:
                body:
                    application/json:
                        schema: !include schemas/residence-nil-rate-band.jsonschema
                        example: !include schemas/residence-nil-rate-band.example
            400:
                body:
                    application/json:
                        schema: !include schemas/residence-nil-rate-band-error.jsonschema
                        example: !include schemas/residence-nil-rate-band-error.example
